### Download Animals Database
GET http://localhost:3000/animals
### Add /x to Download Specific Animal

### Download endagered species
GET http://localhost:3000/animals/endangered

###Downlod by habitat
GET http://localhost:3000/animals/habitat/Forest

###Download by species
GET http://localhost:3000/animals/species?species=Lion

###Add new animal
POST http://localhost:3000/animals
Content-Type: application/json

{
  "name": "Rys",
  "species": "Bobcat",
  "age": 12,
  "isEndangered": true,
  "habitat": "Forest"
}

### Update Animal
PUT http://localhost:3000/animals/1
Content-Type: application/json

{
  "age": 6,
  "habitat": "Jungle"
}

### Delete Animal
DELETE http://localhost:3000/animals/2